2022-07-08 15:36:18,519 | INFO | Check successful
2022-07-08 15:36:18,548 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\yokogawaGS200_tasks.py", line 71, in perform
    value = self.driver.set_range(value,funcVal)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 126, in wrapper
    return method(self, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\yokogawa.py", line 80, in set_range
    print ("range val: " + range_val)
TypeError: can only concatenate str (not "float") to str
2022-07-08 15:36:20,562 | INFO | Process shuting down
