2022-07-06 16:13:53,081 | INFO | Check successful
2022-07-06 16:13:53,115 | INFO | +0.0000E-3
2022-07-06 16:13:53,120 | INFO | +0.00000E+0
2022-07-06 16:13:53,126 | INFO | +0.00000E+0
2022-07-06 16:13:53,131 | INFO | +0.0000E-3
2022-07-06 16:13:53,131 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 307, in wrapper
    return perform(obj, *args, **kwargs)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\task_interface.py", line 86, in perform
    return self.i_perform(*args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\meas_two_res_tasks.py", line 40, in i_perform
    value = self.driver.read_two_resistance()
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 126, in wrapper
    return method(self, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\yokogawa.py", line 325, in read_two_resistance
    return resistance(self)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\yokogawa.py", line 35, in resistance
    value = (volt / current)
ZeroDivisionError: float division by zero
2022-07-06 16:13:55,143 | INFO | Process shuting down
