2022-07-06 15:37:22,013 | INFO | Check successful
2022-07-06 15:37:22,043 | INFO | +0.0000E-3
2022-07-06 15:37:22,047 | INFO | Iterating connection 0/2 for instrument YokogawaGS200
2022-07-06 15:37:22,078 | INFO | Iterating connection 1/2 for instrument YokogawaGS200
2022-07-06 15:37:22,111 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 307, in wrapper
    return perform(obj, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\meas_dc_tasks.py", line 39, in perform
    value = self.driver.read_voltage_dc()
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 126, in wrapper
    return method(self, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\yokogawa.py", line 73, in read_voltage_dc
    raise InstrIOError(msg)
labeq_exopy.instruments.drivers.driver_tools.InstrIOError: Instrument cannot read its voltage when in current mode
2022-07-06 15:37:24,132 | INFO | Process shuting down
